package com.app.wheelie_assistant

import kotlin.String

enum class BTParam {
  B_SYSTEM_TICK,
  B_PREDICTION_HORIZONT,
  B_GYRO_HYSTERESIS,
  B_REVERSED_PITCH,
  B_REVERSED_ROLL,
  B_TARGET_PITCH,
  B_DEAD_ZONE,
  B_EXIT_THRESHOLD,
  B_EMERG_THRESHOLD,
  B_MIN_VOLTAGE,
  B_MIN_STEP,
  B_MAX_STEP,
  B_HYSTERESIS,
  B_MAX_SPEED,
  B_TREND_DURATION,
  B_STABLE_DURATION,

  B_CONNECTED,

  B_ROLL,
  B_PITCH,
  B_VOLTAGE_IN,
  B_VOLTAGE_OUT,
  B_VOLTAGE_MIN,
  B_VOLTAGE_MAX,

  B_GET_SETTINGS,
  B_SET_SETTINGS,

  B_GET_VOLTAGE_RANGE,
  B_RESET_VOLTAGE,

  B_GET_VOLTAGE,
  B_GET_POSITION,

  B_CALIBRATE_GYRO,
  B_CALIBRATE_GYRO_PROG,

  B_OTA_START,
  B_OTA_SUCCESS,
  B_OTA_ERROR,
  B_OTA_MESSAGE,
  B_OTA_PROGRESS,

  B_FIRMWARE_URL,
  B_FIRMWARE_VERSION,

  B_WIFI_SSID,
  B_WIFI_PASS,
  B_WIFI_TIMEOUT,

  B_WIFI_CONNECTING,
  B_WIFI_SUCCESS,
  B_WIFI_ERROR,

  B_GET_STATE,
  B_SET_STATE;

  override fun toString(): String = this.ordinal.toString()
  fun toInt(): Int = this.ordinal
  companion object {
    fun fromInt(ordinal: Int): BTParam? = entries.getOrNull(ordinal)
  }
}
