enum class BTParam {
  B_SYSTEM_TICK,
  B_PREDICTION_HORIZONT,
  B_GYRO_HYSTERESIS,
  B_REVERSED_PITCH,
  B_REVERSED_ROLL,
  B_TARGET_PITCH,
  B_DEAD_ZONE,
  B_EXIT_THRESHOLD,
  B_EMERG_THRESHOLD,
  B_MIN_VOLTAGE,
  B_MIN_STEP,
  B_MAX_STEP,
  B_HYSTERESIS,
  B_MAX_SPEED,
  B_TREND_DURATION,
  B_STABLE_DURATION,

  B_CONNECTED,

  B_ROLL,
  B_PITCH,
  B_VOLTAGE_IN,
  B_VOLTAGE_OUT,
  B_VOLTAGE_MIN,
  B_VOLTAGE_MAX,

  B_ENABLED,
  B_GET_ENABLED,
  B_SET_ENABLED,

  B_SETTINGS,
  B_GET_SETTINGS,
  B_SET_SETTINGS,

  B_GET_VOLTAGE_RANGE,
  B_RESET_VOLTAGE,

  B_GET_VOLTAGE,
  B_GET_POSITION,

  B_WHEELIE,

  B_CALIBRATE_GYRO,
  B_CALIBRATE_GYRO_PROG,

  B_MOTION,
  B_MOTION_AX,
  B_MOTION_AY,
  B_MOTION_AZ,
  B_MOTION_GX,
  B_MOTION_GY,
  B_MOTION_GZ;

  val value: Int
    get() = ordinal

  fun s(): String = value.toString()
}