enum class BTParam(val value: Int) {
  B_SYSTEM_TICK(0),
  B_PREDICTION_HORIZONT(1),
  B_GYRO_HYSTERESIS(2),
  B_REVERSED_PITCH(3),
  B_REVERSED_ROLL(4),
  B_TARGET_PITCH(5),
  B_DEAD_ZONE(6),
  B_EXIT_THRESHOLD(7),
  B_EMERG_THRESHOLD(8),
  B_MIN_VOLTAGE(9),
  B_MIN_STEP(10),
  B_MAX_STEP(11),
  B_HYSTERESIS(12),
  B_MAX_SPEED(13),
  B_TREND_DURATION(14),
  B_STABLE_DURATION(15),

  B_CONNECTED(16),

  B_ROLL(17),
  B_PITCH(18),
  B_VOLTAGE_IN(19),
  B_VOLTAGE_OUT(20),
  B_VOLTAGE_MIN(21),
  B_VOLTAGE_MAX(22),

  B_ENABLED(23),
  B_GET_ENABLED(24),
  B_SET_ENABLED(25),

  B_SETTINGS(26),
  B_GET_SETTINGS(27),
  B_SET_SETTINGS(28),

  B_GET_VOLTAGE_RANGE(29),
  B_RESET_VOLTAGE(30),

  B_GET_VOLTAGE(31),
  B_GET_POSITION(32),

  B_WHEELIE(33),

  B_CALIBRATE_GYRO(34),
  B_CALIBRATE_GYRO_PROG(35),

  B_MOTION(36),
  B_MOTION_AX(37),
  B_MOTION_AY(38),
  B_MOTION_AZ(39),
  B_MOTION_GX(40),
  B_MOTION_GY(41),
  B_MOTION_GZ(42),

  B_FIRMWARE_START(43),
  B_FIRMWARE_ABORT(44),
  B_FIRMWARE_DATA(45),
  B_FIRMWARE_DATA_SIZE(46),
  B_FIRMWARE_SIZE(47),
  B_FIRMWARE_CHECKSUM(48),
  B_FIRMWARE_RECEIVED(49),
  B_FIRMWARE_SUCCESS(50),
  B_FIRMWARE_ERROR(51),
  B_FIRMWARE_MESSAGE(52);

  fun s(): String = value.toString()
}